openapi: 3.1.0
info:
  title: ECHOHUB API
  description: >-
    API Endpoints for the ECHOHUB Project. Team


    #Authentication

    Authentication is a process by which a system verifies the identity of a
    user accessing this API.       


    <!-- ReDoc-Inject: <security-definitions> -->
  version: v1
  termsOfService: https://example.com
  contact:
    name: ECHO Health Inc.
    url: https://echohealthinc.com
    email: Echo_Hub@echohealthinc.com
externalDocs:
  description: |
    description external docs text
  url: 'https://example.server.io'
servers:
  - url: /v1
  
paths:
  #Authorization
  /api/Authentication/v1/Authentication:
    $ref: paths/Authentication/api@RequestAuthentication@V1.yaml
    #eCheck
  /api/eCheck/v1/MPXECheckPayeeContact: 
    $ref: paths/Echecks/api@eCheck@v1@MPXECheckPayeeContact.yaml
  /api/DirectPay/Deluxe/v1/DeluxeEcheck:
    $ref: paths/Echecks/api@DirectPay@Deluxe@v1@DeluxeEcheck.yaml
components:
  securitySchemes:
    x-ApiKey:
      type: apiKey
      name: x-ApiKey
      description: The API key.
      in: header
    x-ClientKey:
      type: apiKey
      description: The client key.
      name: x-ClientKey
      in: header
    ApiKeyAuth:
      type: apiKey
      name: x-Authorization
      in: header
      description: Requests should pass an api_key header.  
    
tags: 
  #Authorization
  - name: Authorization 
    description: |
      This endpoint helps to generate the Authorization Token for accessing the endpoints. 
  #eCheck
  - name: eCheck
    description: |
      An eCheck, or electronic check, is a digital version of a paper check that
      is used to make a payment online.    

      With an eCheck, money is electronically withdrawn from the Payor’s
      checking account. Money is transferred over the ACH (Automated Clearing House) network and
      deposited into the Payee’s checking account.     
